In [12]:
import torch
import torch.nn as nn

In [4]:
a = torch.arange(10).reshape(2, 5)
a.data, a

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]))

In [9]:
a.data.chunk(3, dim=1)

(tensor([[0, 1],
         [5, 6]]),
 tensor([[2, 3],
         [7, 8]]),
 tensor([[4],
         [9]]))

In [11]:
a.data.contiguous()

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
class Example(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 1, 3, padding=1)
        self.conv2 = nn.Conv2d(1, 1, 3, padding=1)

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        return x


In [14]:
ex = Example()

In [18]:
for param in ex.parameters():
    print(param.chunk(2))


(tensor([[[[-0.2680, -0.2500, -0.0980],
          [-0.2188, -0.0952,  0.1542],
          [-0.0848, -0.1648, -0.1779]]]], grad_fn=<SplitBackward0>),)
(tensor([-0.2914], grad_fn=<SplitBackward0>),)
(tensor([[[[ 0.1275, -0.0959, -0.1361],
          [-0.2135,  0.2629, -0.0307],
          [-0.0931,  0.2659,  0.0682]]]], grad_fn=<SplitBackward0>),)
(tensor([0.0173], grad_fn=<SplitBackward0>),)
